[project]
org-name= "wso2"
version= "3.2.0"

[platform]
target = "java8"

    [[platform.libraries]]
    path = "../../../target/org.wso2.micro.gateway.core-3.2.0.jar"

    [[platform.libraries]]
    path = "../../../target/lib/dependencies/org.everit.json.schema-1.5.0.wso2.v1.jar"

    [[platform.libraries]]
    path = "../../../target/lib/dependencies/json-3.0.0.wso2v1.jar"

    [[platform.libraries]]
    path = "../../../target/lib/dependencies/log4j-core-2.13.3.jar"

    [[platform.libraries]]
    path = "../../../target/lib/dependencies/log4j-api-2.13.3.jar"

    [[platform.libraries]]
    path = "../../../target/lib/dependencies/nimbus-jose-jwt-8.8.jar"

    [[platform.libraries]]
    path = "../../../target/lib/dependencies/json-smart-2.3.jar"

    [[platform.libraries]]
    path = "../../../target/lib/dependencies/asm-1.0.2.jar"

    # jackson libraries are added for the use of default claim retriever implementation
    [[platform.libraries]]
    path = "../../../target/lib/dependencies/jackson-annotations-2.9.10.jar"

    [[platform.libraries]]
    path = "../../../target/lib/dependencies/jackson-core-2.9.10.jar"

    [[platform.libraries]]
    path = "../../../target/lib/dependencies/jackson-databind-2.9.10.jar"

[dependencies]
"ballerina/java.jms" = "0.8.1"
